import re

Import('extra_ccflags')
Import('extra_ldflags')
Import('extra_libs')

afk_sources = Glob('*.cpp') + Glob('async/*.cpp') + Glob('data/*.cpp') + Glob('file/*.cpp') + Glob('rng/*.cpp')
afk_libs = ['boost_chrono', 'boost_random', 'boost_system', 'boost_thread', 'GL', 'GLU', 'GLEW', 'OpenCL']
afk_ld_libs = ['m', 'pthread', 'stdc++']
afk_ccflags = ['-Wall', '-Werror']
afk_ldflags = []

Program('afk', afk_sources, LIBS=afk_libs + extra_libs, CCFLAGS=afk_ccflags + extra_ccflags, LINKFLAGS=afk_ldflags + extra_ldflags)

for shader in Glob('shaders/*.glsl'):
    File(shader)

for clProg in Glob('compute/*.cl'):
    File(clProg)

