Import('extra_ccflags')
Import('extra_ldflags')

afk_sources = Glob('*.cpp') + Glob('async/*.cpp') + Glob('rng/*.cpp')
afk_libs = ['boost_random', 'boost_system', 'boost_thread', 'crypto', 'GL', 'GLU', 'GLEW', 'glut', 'OpenCL']
afk_ccflags = ['-Wall', '-Werror']
afk_ldflags = []

Program('afk', afk_sources, LIBS=afk_libs, CCFLAGS=afk_ccflags + extra_ccflags, LINKFLAGS=afk_ldflags + extra_ldflags)

for shader in Glob('shaders/*.glsl'):
    File(shader)

